# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to=b'')),
                ('description', models.TextField()),
            ],
        ),
    ]
